name: Test and Build

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v2
      with:
        toolchain: stable
        components: clippy

    - name: Install dependencies
      run: cargo fetch

    - name: Build the project
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run Clippy
      run: cargo clippy -- -D warnings
